services:
  pikafish:
    build:
      context: .
      dockerfile: Dockerfile.pikafish
    image: game-services-pikafish
    container_name: pikafish
    restart: unless-stopped

  hub:
    build:
      context: .
      dockerfile: Dockerfile
    image: game-services-game-hub
    container_name: game-hub
    restart: unless-stopped
    ports:
      - "8656:8656"
    volumes:
      - .:/www
    depends_on:
      - pikafish
